Source/MvcBoilerplate/Content/bootstrap/site.less
Source/MvcBoilerplate/Web.config
Source/MvcBoilerplateTemplate/Content/bootstrap/site.less
Source/MvcBoilerplateTemplate/Web.config

Add mimeMap to fix "404 not found" error when serving "ghyphicon-halflings-regular.woff2".
Fixed bootstrap glyphicon "404 not found" error. Path missing "/" on bootstrap "site.less".

404 Not Found serving .woff2

---

Source/MVC5/Boilerplate.Web.Mvc5.Sample/Content/Site.css
Source/MVC5/Boilerplate.Web.Mvc5.Sample/Content/Site.less
Source/MVC6/Boilerplate.Web.Mvc6.Sample/Styles/site.scss

Even Microsft ships ASP.NET MVC default template use 50px
for padding-top of body, but in Bootstrap document has stated that
for fixed-top navbar it should use 70px instead.
Closed #33

Change padding-top to 70px for Bootstrap fixed-top navbar

---

Source/Boilerplate.Templates/Content/ApiTemplate/appsettings.json

If the user specifies 'HttpsEverywhere' with value 'false' and immediately starts the project, then in the 'KestrelOptions', the EndPoints field is null, so we get the 'object reference not set to an instance of an object' (KestrelServerOptionsExtensions.ConfigureEndpoints)

Fix API boilerplate (appsettings.json)

---

Source/Content/GraphQLTemplate/Cursor.cs
Tests/Boxed.Templates.Test/GraphQLTemplate/CursorTest.cs

I want to see if there's a way to check if a type is nullable before doing the `Nullable.GetUnderlyingType(type)` but haven't found anything yet.
Anyway, this solved an issue for me where I want to parse the value as an `int?`.

Handle nullable value types in cursor

---

Source/Content/ApiTemplate/Source/ApiTemplate/Startup.cs

Fix for Issue #306 
Now setting the swagger host attribute from the request, as explained here https://github.com/domaindrivendev/Swashbuckle.AspNetCore#modify-swagger-with-request-context

Setting Swagger host attribute

---

build.cake

Use Single() instead of First() because we want this to blow up here and not somewhere inside DotNetCorePack()

Remove hard coded path to Boxed.Templates.csproj file.

---

Tests/Boxed.Templates.FunctionalTest/Framework/ProcessAssert.cs
Tests/Boxed.Templates.FunctionalTest/Framework/ProcessExtensions.cs
appveyor.yml
azure-pipelines.yml
build.cake

- Installs an ASP.NET Core developer certificate as a Cake task, so that we can run `dotnet run` against projects created from a template. This fails on Mac because Azure Pipelines because we don't have admin permissions and fails on Ubuntu because the .NET API to install certificates doesn't exist.
- Enables running `dotnet run` based unit tests on Windows but not Linux and Mac.
- Fix `dotnet run` command that was not cleaning up child processes when we were done with it and wanted to shut down the app.

Install developer certificate and fix dotnet run not cleaning up

---

Docs/NuGet.md
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.template.config/dotnetcli.host.json
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/Source/NuGetTemplate/NuGetTemplate.csproj
Source/NuGetTemplate/Tests/NuGetTemplate.Test/NuGetTemplate.Test.csproj
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs

- Add PublicSign option to NuGet template and disable .NET Framework by default due to an issue.
- Run dotnet test in functional tests.
- Fix health-check-false option.

Add public signing option

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj

Serilog.AspNetCore already includes the following packages we use:
- Serilog.Settings.Configuration
- Serilog.Sinks.Console
- Serilog.Sinks.Debug
- Serilog.Extensions.Hosting

Remove redundant Serilog packages.

---

Source/ApiTemplate/.editorconfig
Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/GraphQLTemplate/.editorconfig
Source/GraphQLTemplate/.template.config/template.json
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/NuGetTemplate/.editorconfig
Source/NuGetTemplate/.template.config/template.json
Source/OrleansTemplate/.editorconfig
Source/OrleansTemplate/.template.config/template.json

- Fix the templating in `.editorconfig` files, so that StyleCop code is removed when it is turned off.
- Make templating in `Dockerfile` better, so the `Dockerfile` is runnable.

Fix the templating in .editorconfig files

---

Source/NuGetTemplate/.github/workflows/build.yml

Stop triggering on tags and trigger on published releases instead.

Change GitHub Action Triggers

---

.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/appveyor.yml
Source/NuGetTemplate/azure-pipelines.yml
appveyor.yml
azure-pipelines.yml

- Always increment build numbers in AppVeyor, since we no longer use the build number and use MinVer for versioning.
- Stop duplicate builds from Branch and PR triggers in GitHub Actions and Azure Pipelines.

Stop Duplicate Builds

---

Source/ApiTemplate/Directory.Build.props
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/ApiTemplate.IntegrationTest.csproj
Source/Boxed.Templates.csproj
Source/GraphQLTemplate/Directory.Build.props
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/GraphQLTemplate.IntegrationTest.csproj
Source/NuGetTemplate/Directory.Build.props
Source/NuGetTemplate/Source/Directory.Build.props
Source/NuGetTemplate/Tests/Directory.Build.props
Source/OrleansTemplate/Directory.Build.props
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

Minor update to add consistency and use `PrivateAssets='all'` for all `xunit.runner.visualstudio` packages.

Use PrivateAssets='all'

---

Source/ApiTemplate/Source/ApiTemplate/Program.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs

Fix based on https://github.com/serilog/serilog-sinks-applicationinsights/issues/121

Register Application Insights with Serilog correctly

---

.gitattributes
Source/ApiTemplate/.gitattributes
Source/ApiTemplate/dotnet-tools.json
Source/GitattributesTemplate/.gitattributes
Source/GraphQLTemplate/.gitattributes
Source/GraphQLTemplate/dotnet-tools.json
Source/NuGetTemplate/.gitattributes
Source/NuGetTemplate/dotnet-tools.json
Source/OrleansTemplate/.gitattributes
Source/OrleansTemplate/dotnet-tools.json
dotnet-tools.json

- Bump Cake.Tool from 0.38.4 to 0.38.5
- Bump Minver.CLI from 2.3.0 to 2.3.1
- Remove duplicate line from `.gitattributes`

Bump Cake.Tool from 0.38.4 to 0.38.5 & Bump Minver.CLI from 2.3.0 to 2.3.1

---

.gitignore
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs

Closes #802 
- Change windows-style paths to cross-platform ones. These changes make the tests pass consequently.
- Also gitignores the .idea folder for anyone using  Jetbrains IDE's such as Rider

Fix Windows-style path seperators in tests

---

Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/TODO.html
Source/GraphQLTemplate/.template.config/dotnetcli.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/GraphQLTemplate/TODO.html
Source/NuGetTemplate/.template.config/dotnetcli.host.json
Source/NuGetTemplate/.template.config/template.json
Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/template.json
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/EnumerableExtensions.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs

- API and GraphQL Templates now open `TODO.html` after project creation.
- Rewrote API and GraphQL Templates `TODO.html`.
- Removed post actions from all templates that restore NuGet packages.
- Added post actions to Orleans template to install and start the Azure Storage Emulator.
- Removed all comments from `template.json` files.

Improve Template Post Actions

---

Source/ApiTemplate/build.cake
Source/GraphQLTemplate/build.cake
Source/OrleansTemplate/build.cake

Fixes https://github.com/Dotnet-Boxed/Templates/issues/818

Fix Cake Publish Task Should Only Publish Source Projects

---

Source/NuGetTemplate/Source/Directory.Build.props
Source/NuGetTemplate/build.cake

- Normalise Source Link File Paths in NuGet Template (see [blog post](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/) for more info). This is recommended for source link.
- Move `SymbolPackageFormat` into `Directory.Build.props`.

Normalise Source Link File Paths in NuGet Template

---

Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/Source/OrleansTemplate.Server/Dockerfile

- Push docker images on GitHub releases and not just on changes pushed to the main branch.
- Use full SDK image for ARM64 support. The alpine image does not currently support ARM64 but will in .NET 6.

Fix Building & Pushing Docker Images

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj

Fix for error occurs in docker Visual Studio 2019 integration:
```
unable to prepare context: path "Z:\\Project\\TrainingPlatform\\TrainingPlatform.API\" " not found
```

Fixing docker-vs integration issue

---

Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/ApiTemplate.IntegrationTest.csproj
Source/ApiTemplate/dotnet-tools.json
Source/ApiTemplate/global.json
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/GraphQLTemplate.IntegrationTest.csproj
Source/GraphQLTemplate/dotnet-tools.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/Tests/Directory.Build.props
Source/NuGetTemplate/dotnet-tools.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj
Source/OrleansTemplate/dotnet-tools.json
Source/OrleansTemplate/global.json
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj
dotnet-tools.json
global.json

- Bump .NET SDK from 5.0.100 to 5.0.102.
- Bump cake.tool to RC2.

Up Bump .NET SDK from 5.0.100 to 5.0.102

---

Source/ApiTemplate/Directory.Build.props
Source/ApiTemplate/Source/ApiTemplate/ApplicationBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/AssemblyInformation.cs
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Program.cs
Source/GraphQLTemplate/Directory.Build.props
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/NuGetTemplate/Directory.Build.props
Source/OrleansTemplate/Directory.Build.props
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs

- Bump StyleCop.Analyzers from 1.1.118 to 1.2.0-beta.321.
- Fix warning in Open Telemetry feature.
- Add AssemblyInformation record to make it easier to get assembly information for API template only.

Bump StyleCop and Open Telemetry Improvements

---

Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/ConfigureSwaggerOptions.cs
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs

- Moves the configuration of Swagger options to a separate class using `IConfigureOptions`.
- Since we don't call `BuildServiceProvider()` anymore, this should speed up startup a little.

Configure Swagger options using IConfigureOptions

---

Source/ApiTemplate/Source/ApiTemplate/Program.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs

Ensures that we still get logs when the application catastrophically fails during initialisation. See https://nblumhardt.com/2020/10/bootstrap-logger/ for more info.
Fixes https://github.com/Dotnet-Boxed/Templates/issues/841

Add Serilog Bootstrap Logger

---

Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/Constants/OpenTelemetryHttpFlavour.cs
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/.template.config/template.json
Source/GraphQLTemplate/Source/GraphQLTemplate/Constants/OpenTelemetryHttpFlavour.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/.template.config/template.json
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Constants/OpenTelemetryHttpFlavour.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs

- Bump `OpenTelemetry.*` from `1.0.0-rc2` to `1.0.0-rc3`.
- `IsAllDataRequested` is now checked for us, so we no longer need to check it.
- Added `OpenTelemetryHttpFlavour` constants.

Bump OpenTelemetry.* from 1.0.0-rc2 to 1.0.0-rc3

---

Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/Program.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs

- Bump `HotChocolate.*` NuGet packages from `11.0.9` to `11.1.0`.
- Remove unnecessary `Newtonsoft.Json` NuGet package.
- Remove unnecessary Hot Chocolate spatial NuGet packages.
- Remove `AllowSynchronousIO` for better performance.
- Remove blank line.

Upgrade Hot Chocolate from v11 to v11.1

---

Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs

Fixes https://github.com/Dotnet-Boxed/Templates/issues/1106.

UseCors Must Come Before UseResponseCaching

---

Source/ApiTemplate/Source/ApiTemplate/Constants/EnvironmentName.cs
Source/ApiTemplate/Source/ApiTemplate/MvcBuilderExtensions.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/CustomWebApplicationFactory.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/MvcBuilderExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs

Fixes https://github.com/Dotnet-Boxed/Templates/issues/1199.
- Add `EnvironmentName.Test` to API template.
- Remove JSON serializer options from GraphQL template, since Hot Chocolate does not support it, see https://github.com/ChilliCream/hotchocolate/issues/4072.

Update JSON Serializer Options

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/HealthChecks/ILocalHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/HealthChecks/IStorageHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/ICounterGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/ICounterStatelessGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/IHelloGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/IReminderGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/CounterGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/CounterStatelessGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/HealthChecks/LocalHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/HealthChecks/StorageHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/HelloGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/ReminderGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Startup.cs
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

- Also switches from `Task` to `ValueTask`.
- Fixes Application Insights option.

Bump Microsoft.Orleans.* from 3.4.3 to 3.5.0

---

Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/DataLoaders/DroidDataLoader.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/DataLoaders/HumanDataLoader.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/Options/GraphQLOptions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/appsettings.json

- Added query field to all mutations.
- Simplified Redis query storage configuration.
- Upgraded complexity configuration for better security.
- Require paging boundaries so that clients need to specify either first, last or take parameters.

Bump HotChocolate from 11.3.8 to 12.0.1

---

.github/workflows/build.yml
Docs/API.md
Docs/NuGet.md
Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/ide.host.json
Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/MvcBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/CustomJsonSerializerContext.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/ApiTemplate.IntegrationTest.csproj
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/CustomWebApplicationFactory.cs
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs

Add Controllers Option

---

Source/ApiTemplate/Source/ApiTemplate/ConfigurationBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/HostExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/ProjectServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/ConfigurationBuilderExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/HostExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/MvcBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ConfigurationBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/HostExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/SiloBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/TraceIdEnricher.cs
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/ReadinessCheck.cs

Use ArgumentNullException.ThrowIfNull

---

Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/OrleansTemplate/Source/OrleansTemplate.Server/Dockerfile

See https://stackoverflow.com/questions/70181870/docker-buildkit-mount-type-cache-for-caching-nuget-packages-for-net-6

Remove Docker buildx --mount=type=cache

---

Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/ApiTemplate/Source/ApiTemplate/Validators/PageOptionsValidator.cs
Source/ApiTemplate/Source/ApiTemplate/Validators/SaveCarValidator.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/PageOptions.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/SaveCar.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs

Switch to fluent validation in preparation for minimal API's in .NET 7.

Add FluentValidation

---

Source/ApiTemplate/build.cake
Source/OrleansTemplate/build.cake

Currently if you use a Dev Container, the cake build picks it up.
Resolves https://github.com/Dotnet-Boxed/Templates/issues/1704

Ignore `.devcontainer` DockerFiles in cake builds.

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/Commands/GetCarPageCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/PatchCarCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/PostCarCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/PutCarCommand.cs
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs

- Validation is now done manually as per the recommendation from `FluentValidation`.
- This sets us up nicely for the switch to minimal API's in .NET 7.

Update to FluentValidation 11.2.1

---

Source/ApiTemplate/build.cake
Source/GraphQLTemplate/build.cake
Source/NuGetTemplate/build.cake
Source/OrleansTemplate/build.cake
build.cake

@ElanHasson I found a slightly easier way to look for .devcontainer directories. Also filling in the GraphQL project cake file.

Ignore Dockerfile's in .devcontainer folders
