Source/Boilerplate.Wizard/Views/MainView.xaml

Fixed a typo in the Boilerplate wizard where "bing" was used in place of "being"

Fixed a small typo 

---

Source/MVC6/Boilerplate.Web.Mvc6.Sample/Startup.ErrorPages.cs

Fixed problem with broken error handling on ReExecute

---

Source/MVC6/Boilerplate.Web.Mvc6.Sample/Controllers/ErrorController.cs

#86 Now such request is changed to 404 NotFound

Fixes problem with returning BadGateway for StatusCodes below 200.

---

Source/MVC5/Boilerplate.Web.Mvc5.Sample/Views/Shared/_Layout.cshtml

Removed trailing slash from manifest json file in the _Layout.cshtml file to fix bug #117.

Bug fix #117, removed trailing slash from manifest json file in _Layout.cshtml 

---

Source/Content/GraphQLTemplate/Source/GraphQLTemplate/InstrumentingGraphQLExecutor.cs

add null check on errors before EnrichWithApolloTracing, fixes #344

add null check on errors before EnrichWithApolloTracing, fixes 344

---

Docs/Orleans.md
Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/template.json
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/HealthChecks/ILocalHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Grains/HealthChecks/IStorageHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/HealthChecks/LocalHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/HealthChecks/StorageHealthCheckGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/HealthChecks/ClusterHealthCheck.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/HealthChecks/GrainHealthCheck.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/HealthChecks/SiloHealthCheck.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/HealthChecks/StorageHealthCheck.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Startup.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs

Add health checks to Orleans template

---

Source/ApiTemplate/Source/ApiTemplate/ApplicationBuilderExtensions.cs
Source/OrleansTemplate/.template.config/template.json
Source/OrleansTemplate/Source/OrleansTemplate.Server/ApplicationBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/Startup.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs

Sets the log level for logs related to health checks to Verbose.

Log health checks as verbose

---

Source/ApiTemplate/Source/ApiTemplate/ApplicationBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/OperationFilters/ApiVersionOperationFilter.cs
Source/ApiTemplate/Source/ApiTemplate/Program.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/PageInfo.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs
Source/ApiTemplate/build.cake
Source/GraphQLTemplate/Source/GraphQLTemplate/ApplicationBuilderExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Program.cs
Source/GraphQLTemplate/build.cake
Source/NuGetTemplate/build.cake
Source/OrleansTemplate/Source/OrleansTemplate.Server/ApplicationBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs
build.cake

Replace '!= null' to 'is object'

---

Docs/NuGet.md
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.template.config/dotnetcli.host.json
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/Directory.Build.props
Source/NuGetTemplate/Directory.Build.targets
Source/NuGetTemplate/NuGetTemplate.sln
Source/NuGetTemplate/Source/Directory.Build.props
Source/NuGetTemplate/Source/NuGetTemplate/NuGetTemplate.csproj
Source/NuGetTemplate/Tests/Directory.Build.props
Source/NuGetTemplate/Tests/NuGetTemplate.Test/NuGetTemplate.Test.csproj
Source/NuGetTemplate/appveyor.yml
Source/NuGetTemplate/azure-pipelines.yml
Source/NuGetTemplate/build.cake

- Use MinVer for versioning
- Use multiple nested Directory.Build.props files
- Add source control providers
- Add source link for more source control providers
- Remove Git option

Use MinVer & Directory.Build.props

---

Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/README.md

Fixes https://github.com/Dotnet-Boxed/Templates/issues/670.

Push from GitHub Actions

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj

Bump Swashbuckle.AspNetCore from 5.4.1 to 5.5.1

---

Docs/NuGet.md
Source/NuGetTemplate/.template.config/template.json

Disable AppVeyor & Azure Pipelines by Default

---

Source/NuGetTemplate/.github/workflows/build.yml

Use Multiple GitHub Actions Jobs to Push Packages

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Bump Microsoft.Orleans from 3.2.0 to 3.2.1

---

Source/Boxed.Templates.csproj

Include files starting with '.' in NuGet package

---

.github/workflows/build.yml
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs
azure-pipelines.yml
build.cake

Parallelize Tests for Each Template for Quicker Build Times

---

.github/workflows/build.yml

Push only after Build and Test jobs have completed

---

.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/appveyor.yml
Source/NuGetTemplate/azure-pipelines.yml
appveyor.yml
azure-pipelines.yml

Add DOTNET_NOLOGO: true

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

Bump Microsoft.Orleans.* from 3.2.1 to 3.2.2

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj

Bump Boxed.Mapping from 4.0.0 to 5.0.0

---

Docs/API.md
Docs/GraphQL.md
Docs/Orleans.md
Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/dotnetcli.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/template.json

Remove Git option to add something better

---

.github/autolabeler.yml
.github/release-drafter.yml
README.md
Source/EditorconfigTemplate/.editorconfig
Source/EditorconfigTemplate/.template.config/icon.png
Source/EditorconfigTemplate/.template.config/template.json
Source/GitattributesTemplate/.gitattributes
Source/GitattributesTemplate/.template.config/icon.png
Source/GitattributesTemplate/.template.config/template.json

Fixes https://github.com/RehanSaeed/EditorConfig/issues/16
```powershell
dotnet new editorconfig
dotnet new gitattributes
```

Add .editorconfig & .gitattributes Item Templates

---

Source/ApiTemplate/Directory.Build.props
Source/GraphQLTemplate/Directory.Build.props
Source/NuGetTemplate/Directory.Build.props
Source/OrleansTemplate/Directory.Build.props
Source/OrleansTemplate/Source/OrleansTemplate.Grains/CounterStatelessGrain.cs
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Bump Microsoft.CodeAnalysis.FxCopAnalyzers from 3.0.0 to 3.3.0

---

Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs

Fix Orleans Application Insights

---

Source/ApiTemplate/Directory.Build.props
Source/GraphQLTemplate/Directory.Build.props
Source/NuGetTemplate/Directory.Build.props
Source/OrleansTemplate/Directory.Build.props
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Set Latest Analysis Level

---

.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml

Workaround bug when pushing to GitHub Packages

---

.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.template.config/template.json
Source/EditorconfigTemplate/.template.config/template.json
Source/GitattributesTemplate/.template.config/template.json
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.template.config/template.json
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.template.config/template.json

Add VS 'New Project' Dialogue Support

---

Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Bump Boxed.DotnetNew from 3.5.0 to 3.6.0

---

Source/ApiTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/build.yml

Use official Docker GitHub Actions

---

Source/ApiTemplate/Source/ApiTemplate/Properties/launchSettings.json
Source/GraphQLTemplate/Source/GraphQLTemplate/Properties/launchSettings.json

See https://devblogs.microsoft.com/dotnet/debug-your-net-core-apps-in-wsl-2-with-visual-studio/

Add WSL 2 Launch Configuration

---

.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/build.yml

actions/setup-dotnet gets .NET version from global.json

---

Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/ApiTemplate/build.cake
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/GraphQLTemplate/build.cake
Source/OrleansTemplate/Source/OrleansTemplate.Server/Dockerfile
Source/OrleansTemplate/build.cake

Add Docker Labels

---

Docs/NuGet.md

Fixes https://github.com/Dotnet-Boxed/Templates/issues/795

Docs Should Refer to snk File Instead of pfx

---

.github/workflows/codeql-analysis.yml
Docs/API.md
Docs/GraphQL.md
Docs/NuGet.md
Docs/Orleans.md
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.template.config/template.json
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.template.config/template.json

See https://github.blog/2020-09-30-code-scanning-is-now-available/

Add GitHub Code Scanning Workflow

---

.editorconfig
Source/ApiTemplate/.editorconfig
Source/EditorconfigTemplate/.editorconfig
Source/GraphQLTemplate/.editorconfig
Source/NuGetTemplate/.editorconfig
Source/OrleansTemplate/.editorconfig

Update .editorconfig from 1.5.0 to 1.6.1

---

.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml

Fixes https://github.com/Dotnet-Boxed/Templates/issues/755

Fix dotnet nuget push

---

Source/ApiTemplate/build.cake
Source/GraphQLTemplate/build.cake
Source/OrleansTemplate/build.cake

Fixes https://github.com/Dotnet-Boxed/Templates/issues/819

Remove Debug Code From Cake Scripts

---

Source/ApiTemplate/Directory.Build.props
Source/GraphQLTemplate/Directory.Build.props
Source/NuGetTemplate/Directory.Build.props
Source/OrleansTemplate/Directory.Build.props
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Bump Microsoft.CodeAnalysis.FxCopAnalyzers from 3.3.0 to 3.3.1

---

Docs/API.md
Docs/GraphQL.md
Docs/Orleans.md
Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/Properties/launchSettings.json
Source/GraphQLTemplate/.template.config/dotnetcli.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/GraphQLTemplate/Source/GraphQLTemplate/Properties/launchSettings.json
Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/template.json

Improve HTTP/HTTPS & Add IIS Expresss Port Parameters

---

Source/ApiTemplate/Source/ApiTemplate/Commands/GetCarPageCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Controllers/CarsController.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs

Fix https://github.com/Dotnet-Boxed/Templates/issues/783

Fix Paging in API Template

---

.editorconfig
Source/ApiTemplate/.editorconfig
Source/EditorconfigTemplate/.editorconfig
Source/GraphQLTemplate/.editorconfig
Source/NuGetTemplate/.editorconfig
Source/OrleansTemplate/.editorconfig

Update .editorconfig to 2.0.1

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/ApiTemplate.IntegrationTest.csproj
Source/ApiTemplate/global.json
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/GraphQLTemplate.IntegrationTest.csproj
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj
global.json

Upgrade to .NET SDK 5.0.101

---

Source/ApiTemplate/dotnet-tools.json
Source/GraphQLTemplate/dotnet-tools.json
Source/OrleansTemplate/dotnet-tools.json

Bump MinVer.Cli from 2.3.1 to 2.4.0

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/HealthChecks/SiloHealthCheck.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

Bump Microsoft.Orleans.* from 3.3.0 to 3.4.0

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj

Bump Serilog.Enrichers.Span from 1.0.1 to 1.1.0

---

Source/NuGetTemplate/appveyor.yml
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/OrleansTemplateTest.cs
appveyor.yml

Fix Mac OS on AppVeyor

---

Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/OrleansTemplate/Source/OrleansTemplate.Server/Dockerfile

@GetoXs Does this resolve the issues you raised in https://github.com/Dotnet-Boxed/Templates/pull/901.

Fix Visual Studio Docker support

---

Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs

Only log Open Telemetry trace data if IsRecording is true

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/Constants/OpenTelemetryAttributeName.cs
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Constants/OpenTelemetryAttributeName.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/Constants/OpenTelemetryAttributeName.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs

Add deployment.name and host.name Open Telemetry Attributes

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

Bump Microsoft.Orleans.* from 3.4.0 to 3.4.1

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj

Bump Swashbuckle.AspNetCore from 5.6.0 to 6.0.0

---

Source/ApiTemplate/dotnet-tools.json
Source/GraphQLTemplate/dotnet-tools.json
Source/NuGetTemplate/dotnet-tools.json
Source/OrleansTemplate/dotnet-tools.json
dotnet-tools.json

Bump Cake.Tool from 1.0.0-rc0002 to 1.0.0

---

Source/ApiTemplate/Directory.Build.props
Source/ApiTemplate/Source/ApiTemplate/ApplicationBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/AssemblyInformation.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/GetCarPageCommand.cs
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Mappers/CarToCarMapper.cs
Source/ApiTemplate/Source/ApiTemplate/Models/Car.cs
Source/ApiTemplate/Source/ApiTemplate/Options/ApplicationOptions.cs
Source/ApiTemplate/Source/ApiTemplate/Repositories/CarRepository.cs
Source/ApiTemplate/Source/ApiTemplate/Repositories/ICarRepository.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/Car.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/Connection.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/PageInfo.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/PageOptions.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/SaveCar.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/CustomWebApplicationFactory.cs

Enable <Nullable> in ApiTemplate Project

---

.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/build.yml

Fixes https://github.com/Dotnet-Boxed/Templates/issues/891

Add GitHub Actions Environments

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/ApiTemplate/ApiTemplate.sln
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/GraphQLTemplate.sln
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/NuGetTemplate.sln
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/OrleansTemplate.sln
Templates.sln

- Also add the CodeQL scanning GitHub Action build to the solutions.

Add GitHub Actions Manual Execution

---

Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json

See https://twitter.com/RehanSaeedUK/status/1364326340191789056?s=20

Open TODO.html on Mac/Linux using bash

---

Source/ApiTemplate/Source/ApiTemplate/MvcBuilderExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/MvcBuilderExtensions.cs

Fixes https://github.com/Dotnet-Boxed/Templates/issues/975

Fix Possible NullReferenceException

---

Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/ApiTemplate/Source/ApiTemplate/MvcBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Properties/launchSettings.json
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/GraphQLTemplate/Source/GraphQLTemplate/Properties/launchSettings.json
Source/OrleansTemplate/Source/OrleansTemplate.Server/Dockerfile
Source/OrleansTemplate/Source/OrleansTemplate.Server/Properties/launchSettings.json

- Fixed running Docker in Visual Studio.
- Move labels to base image in Dockerfile, so they are visible when debugging in Visual Studio.
- Added instructions to run in Docker under HTTPS with a development certificate (See `launchSettings.json`).
- Added new LANG and LC_ALL environment variables.
```dockerfile
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
```

Fix Running in Docker Under Development

---

Source/ApiTemplate/ApiTemplate.sln
Source/GraphQLTemplate/GraphQLTemplate.sln
Source/OrleansTemplate/OrleansTemplate.sln

Fixes https://github.com/Dotnet-Boxed/Templates/issues/982

Remove Tests folder and project when IntegrationTest option disabled

---

Docs/API.md
Docs/GraphQL.md
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/ReadinessCheck.cs

Disable HTTPS by Default

---

.editorconfig
Source/ApiTemplate/.editorconfig
Source/ApiTemplate/Source/ApiTemplate/AssemblyInformation.cs
Source/ApiTemplate/Source/ApiTemplate/Repositories/CarRepository.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs
Source/EditorconfigTemplate/.editorconfig
Source/GraphQLTemplate/.editorconfig
Source/NuGetTemplate/.editorconfig
Source/NuGetTemplate/Source/NuGetTemplate/Class1.cs
Source/OrleansTemplate/.editorconfig
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Bump .editorconfig to 2.1.0

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Up Bump .NET SDK from 5.0.103 to 5.0.200

---

Source/ApiTemplate/build.cake
Source/ApiTemplate/dotnet-tools.json
Source/GraphQLTemplate/build.cake
Source/GraphQLTemplate/dotnet-tools.json
Source/NuGetTemplate/build.cake
Source/NuGetTemplate/dotnet-tools.json
Source/OrleansTemplate/build.cake
Source/OrleansTemplate/dotnet-tools.json
build.cake
dotnet-tools.json

Bump Cake.Tool from 1.0.0 to 1.1.0

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 5.0.200 to 5.0.201

---

Docs/NuGet.md
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/Directory.Build.props
Source/OrleansTemplate/Directory.Build.props
Source/OrleansTemplate/Source/OrleansTemplate.Client/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Grains/ReminderGrain.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Options/ApplicationOptions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Options/StorageOptions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/HelloGrainTest.cs
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj
Tests/Boxed.Templates.FunctionalTest/Models/GraphQLError.cs
Tests/Boxed.Templates.FunctionalTest/Models/GraphQLErrorExtensions.cs

Partially fixes https://github.com/Dotnet-Boxed/Templates/issues/505

Enable C# 8 Nullable Reference Types in Orleans & NuGet Templates

---

Source/ApiTemplate/dotnet-tools.json
Source/GraphQLTemplate/dotnet-tools.json
Source/OrleansTemplate/dotnet-tools.json

Bump MinVer.Cli from 2.4.0 to 2.5.0

---

Source/GraphQLTemplate/Source/GraphQLTemplate/Resolvers/DroidResolver.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Resolvers/HumanResolver.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Resolvers/MutationResolver.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Resolvers/QueryResolver.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Types/DroidObject.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Types/HumanObject.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Types/MutationObject.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Types/QueryObject.cs

Avoid Constructors in Resolvers

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs

Add Redis Health Check

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj

Bump Serilog.Enrichers.Span from 1.1.0 to 1.2.0

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

Bump Microsoft.Orleans.* from 3.4.1 to 3.4.2

---

Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/dotnetcli.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.template.config/dotnetcli.host.json
Source/NuGetTemplate/.template.config/ide.host.json
Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/template.json

- Remove Frameork symbol.
- Ensure ReadMe symbol has a nice name in IDE and CLI.
- Ensure Nullable symbol has a nice name in IDE and CLI.

Fix template JSON configuration

---

.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml

Bump download-artifact from v1 to v2

---

.github/release-drafter.yml
Source/NuGetTemplate/.github/release-drafter.yml

Add GitHub Autolabeler

---

Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj

Bump HotChocolate from 11.1.0 to 11.2.1

---

Source/ApiTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/build.yml

Bump upload-artifact from 1.0.0 to 2.2.3

---

Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json

Fixes https://github.com/Dotnet-Boxed/Templates/issues/1099

Add Default HTTPS Ports

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj

Bump OpenTelemetry.* from 1.0.0-rc3 to 1.0.0-rc4

---

Source/ApiTemplate/.github/dependabot.yml
Source/ApiTemplate/ApiTemplate.sln
Source/GraphQLTemplate/.github/dependabot.yml
Source/GraphQLTemplate/GraphQLTemplate.sln
Source/NuGetTemplate/.github/dependabot.yml
Source/NuGetTemplate/NuGetTemplate.sln
Source/OrleansTemplate/.github/dependabot.yml
Source/OrleansTemplate/OrleansTemplate.sln
Templates.sln

Add Native Dependabot to Templates

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 5.0.202 to 5.0.203

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Add GitHub Actions Permissions

---

Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.template.config/template.json
Source/OrleansTemplate/.template.config/template.json

See https://github.com/sayedihashimi/template-sample/issues/16 and https://github.com/sayedihashimi/template-sample/issues/7

Switch from .NET Project to Solution Template

---

Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.template.config/template.json
Source/OrleansTemplate/.template.config/template.json

Generate new Project GUID's in Solution

---

Docs/API.md
Docs/GraphQL.md
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/template.json
Source/OrleansTemplate/.template.config/template.json

Provide Default Values to all Parameters

---

Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj

Bump Microsoft.Orleans.* from 3.4.2 to 3.4.3

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 5.0.203 to 5.0.301

---

.github/CONTRIBUTING.md

Update Contributing Guide

---

Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs

Log OpenTelemetry to Console and Debug

---

Docs/API.md
Docs/GraphQL.md
Docs/Orleans.md
Source/ApiTemplate/.template.config/ide.host.json
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/ide.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/NuGetTemplate/.template.config/ide.host.json
Source/OrleansTemplate/.template.config/ide.host.json
Source/OrleansTemplate/.template.config/template.json

See https://github.com/sayedihashimi/template-sample/issues/5

Add Custom Choice Labels in VS 16.11

---

Docs/API.md
Docs/GraphQL.md
Docs/Orleans.md
Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/ide.host.json
Source/ApiTemplate/.template.config/template.json
Source/GraphQLTemplate/.template.config/dotnetcli.host.json
Source/GraphQLTemplate/.template.config/ide.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/ide.host.json
Source/OrleansTemplate/.template.config/template.json

Replace Analytics with Application Insights Option

---

Docs/API.md
Docs/GraphQL.md
Source/ApiTemplate/.template.config/dotnetcli.host.json
Source/ApiTemplate/.template.config/ide.host.json
Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Options/ApplicationOptions.cs
Source/ApiTemplate/Source/ApiTemplate/Options/RedisOptions.cs
Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/ApiTemplate/Source/ApiTemplate/appsettings.Development.json
Source/ApiTemplate/Source/ApiTemplate/appsettings.json
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/ApiTemplate.IntegrationTest.csproj
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/CustomWebApplicationFactory.cs
Source/GraphQLTemplate/.template.config/dotnetcli.host.json
Source/GraphQLTemplate/.template.config/ide.host.json
Source/GraphQLTemplate/.template.config/template.json
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/CustomWebApplicationFactory.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/GraphQLTemplate.IntegrationTest.csproj
Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs
Tests/Boxed.Templates.FunctionalTest/GraphQLTemplateTest.cs

Add Distributed Cache Option

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj

Add OpenTelemetry Redis Instrumentation

---

Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/Controllers/CarsController.cs
Source/ApiTemplate/Source/ApiTemplate/MvcBuilderExtensions.cs

Add Expected Output Content Types to Swagger

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 5.0.301 to 5.0.401

---

.github/FUNDING.yml
.github/release-drafter.yml
Source/ApiTemplate/.github/release-drafter.yml
Source/GraphQLTemplate/.github/release-drafter.yml
Source/NuGetTemplate/.github/release-drafter.yml
Source/NuGetTemplate/appveyor.yml
Source/NuGetTemplate/azure-pipelines.yml
Source/OrleansTemplate/.github/release-drafter.yml
appveyor.yml
azure-pipelines.yml

Format yml files

---

Source/Boxed.Templates.csproj

Add NuGet Package README.md

---

Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs

- See https://github.com/ChilliCream/hotchocolate/pull/4294

Add InitializeOnStartup for GraphQL

---

Source/ApiTemplate/Source/ApiTemplate/HostExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/HostExtensions.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/SchemaTest.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/HostExtensions.cs

Use Red Text in Console During Catastrophic Startup Failure

---

Docs/API.md
Docs/GraphQL.md
Docs/NuGet.md
Docs/Orleans.md
Images/VisualStudio-NewProject.png
README.md

Fix embedded NuGet package README.md

---

Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ServiceCollectionExtensions.cs

Improve Open Telemetry Resource Builder

---

Source/ApiTemplate/build.cake
Source/ApiTemplate/dotnet-tools.json
Source/GraphQLTemplate/build.cake
Source/GraphQLTemplate/dotnet-tools.json
Source/NuGetTemplate/build.cake
Source/NuGetTemplate/dotnet-tools.json
Source/OrleansTemplate/build.cake
Source/OrleansTemplate/dotnet-tools.json
build.cake
dotnet-tools.json

Bump Cake.Tool from 1.3.0 to 2.0.0

---

.github/workflows/build.yml
.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Update GitHub Action versions

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 6.0.100 to 6.0.101

---

Source/ApiTemplate/Source/ApiTemplate/Dockerfile
Source/GraphQLTemplate/Source/GraphQLTemplate/Dockerfile
Source/OrleansTemplate/Source/OrleansTemplate.Server/Dockerfile

Add Docker NuGet cache

---

.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Bump release-drafter from 5 to 5.16.1

---

Source/OrleansTemplate/.template.config/dotnetcli.host.json
Source/OrleansTemplate/.template.config/ide.host.json
Source/OrleansTemplate/.template.config/template.json

Use Azurite emulator for Orleans

---

Source/OrleansTemplate/Source/OrleansTemplate.Server/Properties/launchSettings.json
Source/OrleansTemplate/Source/OrleansTemplate.Server/appsettings.Development.json
Source/OrleansTemplate/Source/OrleansTemplate.Server/appsettings.json

Fixes https://github.com/Dotnet-Boxed/Templates/issues/1427.
- https://github.com/Dotnet-Boxed/Templates/issues/1427

Make health check port clearer

---

Source/GraphQLTemplate/Source/GraphQLTemplate/CustomServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj

Add GraphQL Open Telemetry Support

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 6.0.100 to 6.0.102

---

Source/ApiTemplate/Source/ApiTemplate/Startup.cs

Switch from UseSwagger to MapSwagger

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 6.0.102 to 6.0.201

---

Source/NuGetTemplate/README.md

Add NuGet package badge

---

Source/NuGetTemplate/.editorconfig
Source/NuGetTemplate/.template.config/dotnetcli.host.json
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/Directory.Build.props
Source/NuGetTemplate/Source/Directory.Build.props
Source/NuGetTemplate/Source/NuGetTemplate/Class1.cs
Source/NuGetTemplate/Source/NuGetTemplate/NuGetTemplate.csproj
Source/NuGetTemplate/Source/NuGetTemplate/Properties/AssemblyInfo.cs
Source/NuGetTemplate/Tests/NuGetTemplate.Test/NuGetTemplate.Test.csproj
Source/NuGetTemplate/Tests/NuGetTemplate.Test/Properties/AssemblyInfo.cs
Tests/Boxed.Templates.FunctionalTest/NuGetTemplateTest.cs

Add Comments Option

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml

Bump actions/checkout from 3.0.0 to 3.0.1

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Update GitHub Actions Packages

---

Source/ApiTemplate/Source/ApiTemplate/ConfigureOptions/ConfigureJsonOptions.cs
Source/ApiTemplate/global.json
Source/GraphQLTemplate/Source/GraphQLTemplate/ConfigureOptions/ConfigureStaticFileOptions.cs
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/Directory.Build.props
Source/NuGetTemplate/Source/NuGetTemplate/Properties/AssemblyInfo.cs
Source/NuGetTemplate/Tests/NuGetTemplate.Test/Properties/AssemblyInfo.cs
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 6.0.201 to 6.0.300

---

Source/ApiTemplate/build.cake
Source/GraphQLTemplate/build.cake
Source/NuGetTemplate/build.cake
Source/OrleansTemplate/build.cake
build.cake

Add Microsoft Cross-Platform Code Coverage

---

.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Fix autolabeller

---

Source/ApiTemplate/Source/ApiTemplate/OperationFilters/ApiVersionOperationFilter.cs

Use compound assignment

---

Source/ApiTemplate/build.cake
Source/GraphQLTemplate/build.cake
Source/OrleansTemplate/build.cake

Fixes https://github.com/Dotnet-Boxed/Templates/issues/1704

Fail Build on Docker Build Failure

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj

See https://andrewlock.net/using-cancellationtokens-in-asp-net-core-minimal-apis/

Add client request cancelled middleware

---

.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Update release-drafter/release-drafter action to v5.21.0

---

Docs/NuGet.md
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/Source/Directory.Build.props

Fixes https://github.com/Dotnet-Boxed/Templates/issues/1804

Switch to Dotnet.ReproducibleBuilds

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Source/ApiTemplate/Commands/GetCarPageCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/PatchCarCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/PostCarCommand.cs
Source/ApiTemplate/Source/ApiTemplate/Commands/PutCarCommand.cs

Update dependency FluentValidation.AspNetCore to v11.2.2

---

Source/ApiTemplate/Source/ApiTemplate/Program.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Program.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs

Use new Serilog CloseAndFlushAsync

---

.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/build.yml

Publish Test Results Using test-summary/action

---

Source/ApiTemplate/Directory.Build.props
Source/ApiTemplate/build.cake
Source/Boxed.Templates.csproj
Source/GraphQLTemplate/Directory.Build.props
Source/GraphQLTemplate/build.cake
Source/NuGetTemplate/Directory.Build.targets
Source/OrleansTemplate/Directory.Build.props
Source/OrleansTemplate/build.cake

Fix Minver warning

---

Source/ApiTemplate/.template.config/template.json
Source/ApiTemplate/Source/ApiTemplate/AppJsonSerializerContext.cs
Source/ApiTemplate/Source/ApiTemplate/AppServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/ConfigureOptions/ConfigureJsonOptions.cs
Source/ApiTemplate/Source/ApiTemplate/ViewModels/AppJsonSerializerContext.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/AppWebApplicationFactory.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/Controllers/CarsControllerTest.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/HealthCheckTest.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/AppServiceCollectionExtensions.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/AppWebApplicationFactory.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/HealthCheckTest.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/SchemaTest.cs

Rename custom to app

---

Source/ApiTemplate/global.json
Source/GraphQLTemplate/global.json
Source/NuGetTemplate/global.json
Source/OrleansTemplate/global.json
global.json

Bump .NET SDK from 6.0.402 to 7.0.203

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/ApiTemplate.IntegrationTest.csproj
Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/GraphQLTemplate.IntegrationTest.csproj
Source/NuGetTemplate/.template.config/template.json
Source/NuGetTemplate/Source/NuGetTemplate/NuGetTemplate.csproj
Source/NuGetTemplate/Tests/NuGetTemplate.Test/NuGetTemplate.Test.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Abstractions/OrleansTemplate.Abstractions.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Client/OrleansTemplate.Client.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Grains/OrleansTemplate.Grains.csproj
Source/OrleansTemplate/Source/OrleansTemplate.Server/OrleansTemplate.Server.csproj
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/OrleansTemplate.Server.IntegrationTest.csproj
Tests/Boxed.Templates.FunctionalTest/Boxed.Templates.FunctionalTest.csproj

Bump from net6.0 to net7.0

---

Source/ApiTemplate/Source/ApiTemplate/AppServiceCollectionExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/ConfigurationBuilderExtensions.cs
Source/ApiTemplate/Source/ApiTemplate/Program.cs
Source/ApiTemplate/Tests/ApiTemplate.IntegrationTest/AppWebApplicationFactory.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/AppServiceCollectionExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/ConfigurationBuilderExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Program.cs
Source/GraphQLTemplate/Tests/GraphQLTemplate.IntegrationTest/AppWebApplicationFactory.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/ConfigurationBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Program.cs
Source/OrleansTemplate/Tests/OrleansTemplate.Server.IntegrationTest/Fixtures/ClusterFixture.cs

Fix new Visual Studio warnings

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-drafter.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.github/workflows/release-drafter.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.github/workflows/release-drafter.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.github/workflows/release-drafter.yml
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.github/workflows/release-drafter.yml

Bump build action versions

---

.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/build.yml

Bump build action versions 2

---

Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj

Bump to HotChocolate 13

---

Source/ApiTemplate/Source/ApiTemplate/Startup.cs
Source/ApiTemplate/Source/ApiTemplate/TracerProviderBuilderExtensions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Directives/LowerDirectiveType.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Directives/UpperDirectiveType.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Options/RedisOptions.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/Startup.cs
Source/GraphQLTemplate/Source/GraphQLTemplate/TracerProviderBuilderExtensions.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/Startup.cs
Source/OrleansTemplate/Source/OrleansTemplate.Server/TracerProviderBuilderExtensions.cs

Fixes for OpenTelemetry 1.4.0

---

Source/ApiTemplate/Source/ApiTemplate/ApiTemplate.csproj

Bump Swashbuckle from 6.4.0 to 6.5.0

---

Source/ApiTemplate/Source/ApiTemplate/Controllers/CarsController.cs

Remove unnecessary [FromServices] attribute

---

Source/ApiTemplate/Source/ApiTemplate/Properties/launchSettings.json
Source/GraphQLTemplate/Source/GraphQLTemplate/Properties/launchSettings.json
Source/OrleansTemplate/Source/OrleansTemplate.Server/Properties/launchSettings.json
Tests/Boxed.Templates.FunctionalTest/Constants/GraphQlQuery.cs

Restart on rude edit

---

Source/GraphQLTemplate/Source/GraphQLTemplate/GraphQLTemplate.csproj

Bump to HotChocolate 13.1

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
Source/ApiTemplate/.github/workflows/build.yml
Source/ApiTemplate/.github/workflows/codeql-analysis.yml
Source/GraphQLTemplate/.github/workflows/build.yml
Source/GraphQLTemplate/.github/workflows/codeql-analysis.yml
Source/NuGetTemplate/.github/workflows/build.yml
Source/NuGetTemplate/.github/workflows/codeql-analysis.yml
Source/OrleansTemplate/.github/workflows/build.yml
Source/OrleansTemplate/.github/workflows/codeql-analysis.yml

Update actions/checkout to v4

---

Source/ApiTemplate/Tests/.editorconfig
Source/GraphQLTemplate/Tests/.editorconfig
Source/NuGetTemplate/Tests/.editorconfig
Source/OrleansTemplate/Tests/.editorconfig

Workaround bug in Roslyn compiler https://github.com/dotnet/roslyn/issues/41640.

Workaround Bug in Roslyn Compiler
